server:
  port: 8080

spring:
  application:
    name: transaction-manager-api
  datasource:
    url: jdbc:h2:mem:fabrikdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  cloud:
    openfeign:
      client:
        config:
          fabrick:
            #      test-account-id: 14537780
            url: https://sandbox.platfr.io
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            defaultRequestHeaders:
              Auth-Schema: S2S
              Api-Key: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP # ${FABRICK_API_KEY} should be stored as secret


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    csrf:
      ignoring-request-matchers:
        - ant_request_matcher_factory_#getMatcher('/h2-console/**')
  headers:
    frame-options: sameorigin

logging:
  level:
    com.example.fabrik: DEBUG
