server:
  port: 8080

spring:
  application:
    name: transaction-manager-api
  docker:
    compose:
      enabled: false
      file: wiremock/docker-compose.yml

  cloud:
    openfeign:
      client:
        config:
          gbsBanking:
            # test-account-id: 14537780
            url: https://sandbox.platfr.io
            # url: http://localhost:8181 # WireMock server URL
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            defaultRequestHeaders:
              Auth-Schema: S2S
              Api-Key: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP # ${FABRICK_API_KEY} should be stored as secret
