server:
  port: 8080

spring:
  application:
    name: transaction-manager-api
  datasource:
    url: jdbc:h2:mem:fabrikdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  docker:
    compose:
      enabled: false
      file: wiremock/docker-compose.yml

  cloud:
    openfeign:
      client:
        config:
          gbsBanking:
            # test-account-id: 14537780
            url: https://sandbox.platfr.io
            # url: http://localhost:8181 # WireMock server URL
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
            defaultRequestHeaders:
              Auth-Schema: S2S
              Api-Key: FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP # ${FABRICK_API_KEY} should be stored as secret

  security:
    csrf:
      ignoring-request-matchers:
        - ant_request_matcher_factory_#getMatcher('/h2-console/**')
  headers:
    frame-options: sameorigin

logging:
  level:
    com.example.fabrik: DEBUG
